### ISSUE TITLE
0.1.4什么时候上中央仓库呢

### ISSUE THREAD

**Issue by fitz-97** [scx567888/live-room-watcher#126]
目前0.1.3抖音的还是RENDER_DATA旧版，有看到源码0.1.4有更新
作者大大计划什么时候上中央仓库哇

**Comment by scx567888** [comment]
明天早上吧

**Comment by fitz-97** [comment]
啊还有好像目前这个0.1.4我这好像jdk21才能跑，如果是的话建议在readme里面标注一下友好一点 hhh

**Comment by fitz-97** [comment]
> 明天早上吧

啊还有好像目前这个0.1.4我这好像jdk21才能跑，如果是的话建议在readme里面标注一下友好一点 hhh
