### ISSUE TITLE
类文件具有错误的版本 65.0, 应为 62.0     请删除该文件或确保该文件位于正确的类路径子目录中。

### ISSUE THREAD

**Issue by Hoiyi** [scx567888/live-room-watcher#146]
类文件具有错误的版本 65.0, 应为 62.0
    请删除该文件或确保该文件位于正确的类路径子目录中。

**Comment by Hoiyi** [comment]
无法访问cool.scx.util.HashUtils
  错误的类文件: /Library/Java/repository/cool/scx/scx-common/2.4.9/scx-common-2.4.9.jar!/cool/scx/util/HashUtils.class
    类文件具有错误的版本 65.0, 应为 62.0
    请删除该文件或确保该文件位于正确的类路径子目录中

**Comment by scx567888** [comment]
用 jdk21
