### ISSUE TITLE
1.java版本对应是多少。2.能够将依赖工程放到一个里面，部署方便

### ISSUE THREAD

**Issue by jiangzituozou** [scx567888/live-room-watcher#15]
有问题请教一下。1.java版本对应是多少。2.能够将依赖工程放到一个里面，部署方便

**Comment by scx567888** [comment]
1, java 版本是 17
2, 这是个 maven 项目...

**Comment by jiangzituozou** [comment]
我的意思这个工程还要依赖你的别的scx-parent、scx-common工程，能否把其他工程的东西直接放进来，毕竟里面的东西不多，没必要解耦啊

**Comment by scx567888** [comment]
依赖其他工具包是很正常的, 根目录有一个 script.bat 你可以修改其中的 JAVA_HOME 和 MAVEN_HOME 然后开启
![image](https://user-images.githubusercontent.com/75682569/216036994-13d540ec-4b55-40c6-be97-e213ac3bd1cd.png)
这样运行 script.bat 可以直接运行项目 或者打包成可执行 jar

**Comment by scx567888** [comment]
况且 scx-common 压根就不是为了这个而创建的, 我很多私人项目都用到了

**Comment by scx567888** [comment]
pom.xml 中
```
 <scx.mainClass>cool.scx.live_room_watcher.Main</scx.mainClass> 
```
修改这个便可以设置运行时的 入口类

**Comment by jiangzituozou** [comment]
我是不是还要把依赖的其他两个工程拉下来打成jar包放到MAVEN_HOME里面

**Comment by scx567888** [comment]
以后这个完善后也可能发布的中央仓库,我会提供一定程度的开放接口, 届时可以像 sdk 一样直接使用, 直到抖音官方推出 sdk 为止

**Comment by jiangzituozou** [comment]
好的，大佬可以的，后期甚至可以做一个saas服务集中获取很多账号的直播弹幕放到统一的消息服务里面

**Comment by scx567888** [comment]
鉴于总有人搞不清项目所需的 jdk 版本以及 运行方式 我重新开启此 issues
