### ISSUE TITLE
Test用例跑起来提示jdk版本要高于20

### ISSUE THREAD

**Issue by Qilin-Xiao** [scx567888/live-room-watcher#205]

**Comment by Qilin-Xiao** [comment]
能不能考虑兼容下JDK8呀，webosokect里调用异步线程那些方法也还是预览API。

java: ofVirtual() 是预览 API，默认情况下处于禁用状态。
  （请使用 --enable-preview 以启用预览 API）

**Comment by scx567888** [comment]
您可以使用 jdk21 来运行
