### ISSUE TITLE
快手官方弹幕获取

### ISSUE THREAD

**Issue by YangYu8510** [scx567888/live-room-watcher#226]
看到里面有一个roundId，想问一下这个是什么

**Comment by scx567888** [comment]
参见 快手官方 https://mp.kuaishou.com/miniPlayDocs/technologyrelated/Affiliatedability/basicability/quickaccess.html

**Comment by YangYu8510** [comment]
okok，这个是弹幕游戏类的应用是吧，了解了，谢谢大哥
