### ISSUE TITLE
抖音语音直播解析错误感觉json结构变了下面是报错信息。复现。过程打开抖音现在语音直播输入房间号

### ISSUE THREAD

**Issue by nowshowtime3** [scx567888/live-room-watcher#232]
/Library/Java/JavaVirtualMachines/jdk-21.jdk/Contents/Home/bin/java -javaagent:/Applications/IntelliJ IDEA CE.app/Contents/lib/idea_rt.jar=65085:/Applications/IntelliJ IDEA CE.app/Contents/bin -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath /Users/chenkang/Desktop/code/untitled/target/classes:/Users/chenkang/.m2/repository/cool/scx/live-room-watcher/0.3.2/live-room-watcher-0.3.2.jar:/Users/chenkang/.m2/repository/cool/scx/scx-common/3.0.0/scx-common-3.0.0.jar:/Users/chenkang/.m2/repository/io/vertx/vertx-core/4.5.8/vertx-core-4.5.8.jar:/Users/chenkang/.m2/repository/io/netty/netty-common/4.1.110.Final/netty-common-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-buffer/4.1.110.Final/netty-buffer-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-transport/4.1.110.Final/netty-transport-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-handler/4.1.110.Final/netty-handler-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.110.Final/netty-transport-native-unix-common-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-codec/4.1.110.Final/netty-codec-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-handler-proxy/4.1.110.Final/netty-handler-proxy-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-codec-socks/4.1.110.Final/netty-codec-socks-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-codec-http/4.1.110.Final/netty-codec-http-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-codec-http2/4.1.110.Final/netty-codec-http2-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-resolver/4.1.110.Final/netty-resolver-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-resolver-dns/4.1.110.Final/netty-resolver-dns-4.1.110.Final.jar:/Users/chenkang/.m2/repository/io/netty/netty-codec-dns/4.1.110.Final/netty-codec-dns-4.1.110.Final.jar:/Users/chenkang/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.17.1/jackson-core-2.17.1.jar:/Users/chenkang/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.17.1/jackson-datatype-jsr310-2.17.1.jar:/Users/chenkang/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.17.1/jackson-annotations-2.17.1.jar:/Users/chenkang/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.17.1/jackson-databind-2.17.1.jar:/Users/chenkang/.m2/repository/com/fasterxml/jackson/dataformat/jackson-dataformat-xml/2.17.1/jackson-dataformat-xml-2.17.1.jar:/Users/chenkang/.m2/repository/org/codehaus/woodstox/stax2-api/4.2.2/stax2-api-4.2.2.jar:/Users/chenkang/.m2/repository/com/fasterxml/woodstox/woodstox-core/6.6.2/woodstox-core-6.6.2.jar:/Users/chenkang/.m2/repository/org/springframework/spring-context/6.1.8/spring-context-6.1.8.jar:/Users/chenkang/.m2/repository/org/springframework/spring-aop/6.1.8/spring-aop-6.1.8.jar:/Users/chenkang/.m2/repository/org/springframework/spring-beans/6.1.8/spring-beans-6.1.8.jar:/Users/chenkang/.m2/repository/org/springframework/spring-core/6.1.8/spring-core-6.1.8.jar:/Users/chenkang/.m2/repository/org/springframework/spring-jcl/6.1.8/spring-jcl-6.1.8.jar:/Users/chenkang/.m2/repository/org/springframework/spring-expression/6.1.8/spring-expression-6.1.8.jar:/Users/chenkang/.m2/repository/io/micrometer/micrometer-observation/1.12.6/micrometer-observation-1.12.6.jar:/Users/chenkang/.m2/repository/io/micrometer/micrometer-commons/1.12.6/micrometer-commons-1.12.6.jar:/Users/chenkang/.m2/repository/org/jasypt/jasypt/1.9.3/jasypt-1.9.3.jar:/Users/chenkang/.m2/repository/net/java/dev/jna/jna-platform/5.14.0/jna-platform-5.14.0.jar:/Users/chenkang/.m2/repository/net/java/dev/jna/jna/5.14.0/jna-5.14.0.jar:/Users/chenkang/.m2/repository/cool/scx/scx-logging/3.0.0/scx-logging-3.0.0.jar:/Users/chenkang/.m2/repository/com/google/protobuf/protobuf-java/4.27.0/protobuf-java-4.27.0.jar:/Users/chenkang/.m2/repository/org/jsoup/jsoup/1.17.2/jsoup-1.17.2.jar:/Users/chenkang/.m2/repository/org/graalvm/js/js/23.0.4/js-23.0.4.jar:/Users/chenkang/.m2/repository/org/graalvm/regex/regex/23.0.4/regex-23.0.4.jar:/Users/chenkang/.m2/repository/org/graalvm/truffle/truffle-api/23.0.4/truffle-api-23.0.4.jar:/Users/chenkang/.m2/repository/org/graalvm/sdk/graal-sdk/23.0.4/graal-sdk-23.0.4.jar:/Users/chenkang/.m2/repository/com/ibm/icu/icu4j/72.1/icu4j-72.1.jar:/Users/chenkang/.m2/repository/org/slf4j/slf4j-api/2.0.13/slf4j-api-2.0.13.jar Main
解析中...
Exception in thread "main" java.lang.RuntimeException: 解析 直播间错误 !!!
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomWatcher.startWatch(DouYinHackLiveRoomWatcher.java:156)
	at Main.main(Main.java:20)
Caused by: java.lang.NullPointerException: Cannot read field "title" because "douYinApp.state.roomStore.roomInfo.room" is null
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomInfo.liveRoomTitle(DouYinHackLiveRoomInfo.java:39)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomWatcher.liveRoomTitle(DouYinHackLiveRoomWatcher.java:468)
	at cool.scx.live_room_watcher.impl.douyin_hack.DouYinHackLiveRoomWatcher.startWatch(DouYinHackLiveRoomWatcher.java:154)
	... 1 more

**Comment by scx567888** [comment]
更新了试试

**Comment by nowshowtime3** [comment]
好嘞
