### ISSUE TITLE
maven打包后，执行jar包报错

### ISSUE THREAD

**Issue by ChickenWingOne** [scx567888/live-room-watcher#32]
运行命令： java -jar live-room-watcher-0.0.4.jar 
执行报错如下：
Exception in thread "main" java.lang.NoClassDefFoundError: io/netty/handler/codec/http/cookie/Cookie
        at cool.scx.live_room_watcher.Main.main(Main.java:8)
Caused by: java.lang.ClassNotFoundException: io.netty.handler.codec.http.cookie.Cookie
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more

**Comment by ChickenWingOne** [comment]
很奇怪，idea直接可以Main方法是没有问题的

**Comment by scx567888** [comment]
看这个 https://github.com/scx567888/live-room-watcher/issues/15

**Comment by ChickenWingOne** [comment]
我和那个不是同一个问题，我用的就是jdk17，mvn clean package打出的jar包直接跑的，然后就报出这个错误了

**Comment by scx567888** [comment]
本质上就是一个问题 你需要在打完包的同时 确保所需的依赖存在 lib 下, 因为这个默认打包并不是 fat jar, 你可以使用我编写的 script.bat 脚本 也可以自行拷贝依赖, 基本说明 issue #15 里面有

**Comment by scx567888** [comment]
鉴于总有人搞不清项目所需的 jdk 版本以及 运行方式 我重新开启此 issues

**Comment by miraclestar** [comment]
同样的报错；
用的是java 17，script脚本打的包；
start.bat 执行的
![image](https://github.com/scx567888/live-room-watcher/assets/1502697/4dc9a782-bb00-4c4f-baa2-69b44bb2275c)

**Comment by scx567888** [comment]
请提供  live-room-watcher-0.0.5.jar/META-INF/MANIFEST.MF 的内容
以及 lib 目录的内容

**Comment by miraclestar** [comment]
> 请提供 live-room-watcher-0.0.5.jar/META-INF/MANIFEST.MF 的内容 以及 lib 目录的内容
这是MANIFEST.MF ：

Manifest-Version: 1.0
Created-By: Maven JAR Plugin 3.3.0
Build-Jdk-Spec: 17
Class-Path: libs/scx-common-2.2.9.jar libs/vertx-core-4.4.4.jar libs/net
 ty-common-4.1.94.Final.jar libs/netty-buffer-4.1.94.Final.jar libs/nett
 y-transport-4.1.94.Final.jar libs/netty-handler-4.1.94.Final.jar libs/n
 etty-transport-native-unix-common-4.1.94.Final.jar libs/netty-codec-4.1
 .94.Final.jar libs/netty-handler-proxy-4.1.94.Final.jar libs/netty-code
 c-socks-4.1.94.Final.jar libs/netty-codec-http-4.1.94.Final.jar libs/ne
 tty-codec-http2-4.1.94.Final.jar libs/netty-resolver-4.1.94.Final.jar l
 ibs/netty-resolver-dns-4.1.94.Final.jar libs/netty-codec-dns-4.1.94.Fin
 al.jar libs/jackson-core-2.15.0.jar libs/jackson-datatype-jsr310-2.15.2
 .jar libs/jackson-annotations-2.15.2.jar libs/jackson-databind-2.15.2.j
 ar libs/jackson-dataformat-xml-2.15.2.jar libs/stax2-api-4.2.1.jar libs
 /woodstox-core-6.5.1.jar libs/jasypt-1.9.3.jar libs/jna-platform-5.13.0
 .jar libs/jna-5.13.0.jar libs/protobuf-java-3.23.4.jar
Implementation-Title: live-room-watcher
Implementation-Version: 0.0.5
Main-Class: cool.scx.live_room_watcher.Main

这是libs下的：
![image](https://github.com/scx567888/live-room-watcher/assets/1502697/794a1ca3-c631-4f2e-a42d-e3c78d8e02e0)

**Comment by miraclestar** [comment]
谢谢，更新pom可以了，点赞！
