### ISSUE TITLE
关于cookie的添加

### ISSUE THREAD

**Issue by pangrj007** [scx567888/live-room-watcher#47]
添加登录后的cookie  在榜单上可以看见我登录的账号进入了

**Comment by scx567888** [comment]
是这是陈述还是想要这个功能

**Comment by pangrj007** [comment]
我想要这个功能   我有做好的登录的Cookie ，  就是做直播虚拟人气

**Comment by scx567888** [comment]
是想在连接到直播间的时候 传递你自定义的 cookie吗?

**Comment by scx567888** [comment]
我不清楚抖音的人气机制 不能保证能通过这种方式增加人气 但是自定义 cookie 是可以的

**Comment by pangrj007** [comment]
我也是刚转抖音过来 我以前做快手的   我看了下就是Cookie的控制
