### ISSUE TITLE
有时候返回200的一个可能原因

### ISSUE THREAD

**Issue by LyzenX** [scx567888/live-room-watcher#50]
在我的一台linux服务器上(这台服务器可能因为频繁访问抖音而受到了部分限制)，发现当ws链接中的fetch_time太旧时，多次重试均返回200。当fetch_time的值改为`System.currentTimeMillis()`后，可以获取弹幕。另外，在一个新线程中启动弹幕获取，如果该线程不是守护线程，也会返回200。但在我Windows系统的机器上均未出现上述情况。

**Comment by scx567888** [comment]
非常感谢 !!!😁
